import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        // ── Brand (blue scale) ────────────────────────────
        brand: {
          50:  "#fafcff",
          150: "#e7f1fc",
          250: "#bad1f5",
          350: "#6ca5fe",
          500: "#0b49ea",
          550: "#0f3db5",
          650: "#082485",
          750: "#001f5a",
          850: "#000c36",
          900: "#000c36",
        },
        // ── Neutral (grey scale) ──────────────────────────
        neutral: {
          50:   "#ffffff",
          100:  "#f9fafb",
          150:  "#f6f7f8",
          200:  "#f2f4f5",
          250:  "#e9ecee",
          300:  "#e0e3e6",
          350:  "#d6dade",
          400:  "#cbd0d4",
          450:  "#bfc4c8",
          500:  "#b0b6bb",
          550:  "#9ea4a8",
          600:  "#8a9196",
          650:  "#7f868a",
          700:  "#72797d",
          750:  "#656c70",
          800:  "#5a6064",
          850:  "#4c5256",
          900:  "#3f464b",
          950:  "#2f353a",
          1000: "#25292d",
          1050: "#1c1f22",
          1100: "#111315",
        },
        // ── Status — success ──────────────────────────────
        success: {
          accent: "#348347",
          light:  "#f8fbf8",
          stroke: "#cde2d2",
        },
        // ── Status — error ────────────────────────────────
        error: {
          accent: "#cc2330",
          light:  "#fef6f7",
          stroke: "#f7c2c5",
        },
        // ── Status — warning ──────────────────────────────
        warning: {
          accent: "#ee7624",
          light:  "#fffdfc",
          stroke: "#fdcaa7",
        },
        // ── Status — info ─────────────────────────────────
        info: {
          accent: "#0b49ea",
          light:  "#fafcff",
          stroke: "#d2e3f9",
        },
        // ── Blue primitives ───────────────────────────────
        blue: {
          50:  "#fafcff",
          100: "#f5fafe",
          150: "#e7f1fc",
          200: "#d2e3f9",
          250: "#bad1f5",
          300: "#96bcf8",
          350: "#6ca5fe",
          400: "#4985fd",
          450: "#2662fc",
          500: "#0b49ea",
          550: "#0f3db5",
          600: "#0b309d",
          650: "#082485",
          700: "#032372",
          750: "#001f5a",
          800: "#00164d",
          850: "#000c36",
        },
        // ── Green primitives ──────────────────────────────
        green: {
          50:  "#f8fbf8",
          100: "#edf4ee",
          200: "#cde2d2",
          300: "#93be9c",
          400: "#60a478",
          500: "#348347",
          600: "#2a6e3a",
          700: "#20592e",
          800: "#174423",
          900: "#0f3018",
        },
        // ── Red primitives ────────────────────────────────
        red: {
          50:  "#fef6f7",
          100: "#fce9ea",
          200: "#f7c2c5",
          300: "#ed838a",
          400: "#e55057",
          500: "#cc2330",
          600: "#a81c28",
          700: "#85151f",
          800: "#620e17",
          900: "#3f080f",
        },
        // ── Orange primitives ─────────────────────────────
        orange: {
          50:  "#fffdfc",
          100: "#feede4",
          200: "#fdcaa7",
          300: "#fca166",
          400: "#f9873e",
          500: "#ee7624",
          600: "#c45d1c",
          700: "#9a4615",
          800: "#702f0e",
          900: "#461907",
        },
        // ── Chart colors ──────────────────────────────────
        "chart-denim": {
          100: "#dae5f8",
          200: "#a9c2ed",
          300: "#779fe3",
          400: "#477cd9",
          500: "#0a51cc",
          600: "#063c99",
          700: "#052c70",
          800: "#021638",
          900: "#010d21",
        },
        "chart-azure": {
          100: "#d9f1ff",
          200: "#a6ddff",
          300: "#73c9ff",
          400: "#3fb7ff",
          500: "#009fff",
          600: "#0077bf",
          700: "#00578c",
          800: "#002c45",
          900: "#001a2b",
        },
        "chart-green": {
          100: "#d9f6ec",
          200: "#a8ead2",
          300: "#78ddb8",
          400: "#47d19f",
          500: "#03c37e",
          600: "#07915f",
          700: "#066a45",
          800: "#023522",
          900: "#011f15",
        },
        "chart-orange": {
          100: "#ffe7db",
          200: "#ffc6ad",
          300: "#ffa57e",
          400: "#ff854f",
          500: "#ff5c14",
          600: "#bf450f",
          700: "#8c320a",
          800: "#451905",
          900: "#2a0f02",
        },
        chetwode: {
          100: "#e6e7f9",
          200: "#c5c7ef",
          300: "#a4a7e5",
          400: "#8387dc",
          500: "#5a5fd0",
          600: "#43489c",
          700: "#313472",
          800: "#171939",
          900: "#0f0f22",
        },
        // ── Transparent overlays ──────────────────────────
        "white-overlay": {
          10: "#ffffff1a",
          20: "#ffffff33",
          30: "#ffffff4d",
          40: "#ffffff66",
          50: "#ffffff80",
          60: "#ffffff99",
          70: "#ffffffb3",
          80: "#ffffffcc",
          90: "#ffffffe6",
        },

        // ── Semantic layer (CSS vars → theme-switchable) ──
        // Usage: text-content-primary, bg-surface-background,
        //        border-stroke-default, text-icon-brand, etc.
        content: {
          primary:     "var(--color-text-primary)",
          secondary:   "var(--color-text-secondary)",
          disabled:    "var(--color-text-disabled)",
          inverse:     "var(--color-text-inverse)",
          "dark-accent": "var(--color-text-dark-accent)",
          selected:    "var(--color-text-selected)",
          link: {
            DEFAULT:  "var(--color-text-link-default)",
            hover:    "var(--color-text-link-hover)",
            visited:  "var(--color-text-link-visited)",
            pressed:  "var(--color-text-link-pressed)",
            disabled: "var(--color-text-link-disabled)",
          },
        },
        surface: {
          background:      "var(--color-surface-background)",
          foreground:      "var(--color-surface-foreground)",
          "foreground-dark":"var(--color-surface-foreground-dark)",
          dashboard:       "var(--color-surface-dashboard)",
          drawer:          "var(--color-surface-drawer)",
          widget:          "var(--color-surface-widget)",
          popover:         "var(--color-surface-popover)",
          hover:           "var(--color-surface-hover)",
          selected:        "var(--color-surface-selected)",
          accent:          "var(--color-surface-accent)",
          focused:         "var(--color-surface-focused)",
          input: {
            DEFAULT:  "var(--color-surface-input-default)",
            disabled: "var(--color-surface-input-disabled)",
            locked:   "var(--color-surface-input-locked)",
          },
          chip: {
            DEFAULT:  "var(--color-surface-chip-default)",
            hover:    "var(--color-surface-chip-hover)",
            selected: "var(--color-surface-chip-selected)",
            white:    "var(--color-surface-chip-white)",
          },
          table: {
            row:      "var(--color-surface-table-row)",
            "row-hover":     "var(--color-surface-table-row-hover)",
            "row-selected":  "var(--color-surface-table-row-selected)",
            header:   "var(--color-surface-table-header)",
            level1:   "var(--color-surface-table-level1)",
            level2:   "var(--color-surface-table-level2)",
            level3:   "var(--color-surface-table-level3)",
            focus:    "var(--color-surface-table-focus)",
          },
          toggle: {
            DEFAULT:  "var(--color-surface-toggle-default)",
            active:   "var(--color-surface-toggle-active)",
            disabled: "var(--color-surface-toggle-disabled)",
            focused:  "var(--color-surface-toggle-focused)",
            ellipse:  "var(--color-surface-toggle-ellipse)",
          },
          nav: {
            DEFAULT:  "var(--color-surface-nav-default)",
            hover:    "var(--color-surface-nav-hover)",
            "hover-selected": "var(--color-surface-nav-hover-selected)",
            selected: "var(--color-surface-nav-selected)",
          },
          progress: {
            active:      "var(--color-surface-progress-active)",
            foreground:  "var(--color-surface-progress-foreground)",
          },
          intercom: {
            success: "var(--color-intercom-success)",
            error:   "var(--color-intercom-error)",
            warning: "var(--color-intercom-warning)",
            info:    "var(--color-intercom-info)",
          },
        },
        stroke: {
          DEFAULT:            "var(--color-stroke-default)",
          dark:               "var(--color-stroke-dark)",
          light:              "var(--color-stroke-light)",
          brand:              "var(--color-stroke-brand)",
          table:              "var(--color-stroke-table)",
          "controls-default":  "var(--color-stroke-controls-default)",
          "controls-disabled": "var(--color-stroke-controls-disabled)",
          "controls-hover":    "var(--color-stroke-controls-hover)",
        },
        icon: {
          brand:    "var(--color-icon-brand)",
          dark:     "var(--color-icon-dark)",
          white:    "var(--color-icon-white)",
          hover:    "var(--color-icon-hover)",
          disabled: "var(--color-icon-disabled)",
          link: {
            DEFAULT:  "var(--color-icon-link-default)",
            hover:    "var(--color-icon-link-hover)",
            visited:  "var(--color-icon-link-visited)",
            pressed:  "var(--color-icon-link-pressed)",
            disabled: "var(--color-icon-link-disabled)",
          },
        },
        nav: {
          active:          "var(--color-nav-active)",
          hover:           "var(--color-nav-hover)",
          accent:          "var(--color-nav-accent)",
          "dark-accent":   "var(--color-nav-dark-accent)",
          selected:        "var(--color-nav-selected)",
          "text-selected": "var(--color-nav-text-selected)",
        },
        ai: {
          surface:      "var(--color-ai-surface)",
          "surface-hover":"var(--color-ai-surface-hover)",
          icon:         "var(--color-ai-icon)",
          text:         "var(--color-ai-text-default)",
          "text-hover": "var(--color-ai-text-hover)",
        },
      },
      // ── Typography ──────────────────────────────────────
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
      },
      fontSize: {
        "ds-xs":  ["12px", { lineHeight: "16px" }],
        "ds-sm":  ["14px", { lineHeight: "20px" }],
        "ds-md":  ["16px", { lineHeight: "24px" }],
        "ds-lg":  ["20px", { lineHeight: "24px" }],
        "ds-xl":  ["24px", { lineHeight: "28px" }],
        "ds-2xl": ["28px", { lineHeight: "32px" }],
        "ds-3xl": ["32px", { lineHeight: "36px" }],
      },
      fontWeight: {
        light:     "300",
        regular:   "400",
        semibold:  "600",
        bold:      "700",
        extrabold: "800",
      },
      // ── Spacing ─────────────────────────────────────────
      spacing: {
        "sp-1":  "1px",
        "sp-2":  "2px",
        "sp-3":  "3px",
        "sp-4":  "4px",
        "sp-6":  "6px",
        "sp-8":  "8px",
        "sp-12": "12px",
        "sp-16": "16px",
        "sp-24": "24px",
        "sp-32": "32px",
        "sp-40": "40px",
        "sp-48": "48px",
        "sp-64": "64px",
        "sp-80": "80px",
        "sp-96": "96px",
      },
      // ── Border radius ────────────────────────────────────
      borderRadius: {
        xxs: "2px",
        xs:  "4px",
        s:   "8px",
        m:   "12px",
        l:   "16px",
        xl:  "24px",
        xxl: "32px",
      },
      // ── Box shadow ───────────────────────────────────────
      boxShadow: {
        sm: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
        md: "0 4px 6px -1px rgb(0 0 0 / 0.08)",
        lg: "0 10px 15px -3px rgb(0 0 0 / 0.08)",
      },
    },
  },
  plugins: [],
};

export default config;
